exports.check = require('./check')
exports.register = require('./register')
exports.registerCheck = require('./registerCheck')
exports.deleteDomain = require('./deleteDomain')
exports.renew = require('./renew')
exports.notifications = require('./notifications')
exports.updateDomain = require('./updateDomain')
